### ISSUE TITLE
API edit license return a 500 error 

### ISSUE THREAD

**Issue by naja7host** [enverido/php#2]
the API edit license return a 500 error , the lookup command return  valid response . 

	// Get The licence ID by Short Code
        $license = $this->api->get('/lookup', [
            'shortcode' => $vars['license_id']
        ]);

        if(isset($vars['license_ip'])) {
            $params['ip'] = $this->Html->ifSet($vars['license_ip']);
        }

        if(isset($vars['license_domain'])) {
            $params['domain'] = $this->Html->ifSet($vars['license_domain']);
        }

		$response = $this->api->patch('/product/'. $license->product_id .'/licence/'. $license->licence_id, [
			'form_params' => $params
		]);

the response error is 

Server error: `PATCH https://username.enverido.com/product/12/licence/26` resulted in a `500 Internal Server Error` response: {"error":"","code":500}

**Comment by BnMcG** [comment]
I'll look into this now for you. Expect an update in the next hour or two. Can you confirm that $params['ip'] and $params['domain'] are both set correctly?

Cheers.

**Comment by naja7host** [comment]
the request has a empty  $params['ip'] , and  $params['domain'] has a value

**Comment by BnMcG** [comment]
It looks like you aren't passing an email address with your request. Take a look at the documentation here: https://docs.cogative.com/pages/viewpage.action?pageId=1409460#id-/{LICENCE-ID}-PATCH

In addition to the new IP or domain name, you also need to provide an email address - even if it's the same as the current one. 

I'll look into why this is throwing a 500 error and not a 4xx. 

Hope this helps.

**Comment by BnMcG** [comment]
For reference, this sort of error should respond with a 400 code and a message giving some explanation of the issue.

**Comment by BnMcG** [comment]
We've deployed a fix so that a missing email field should return a 400 error with a useful message now. You're welcome to give it another go to confirm it's working as expected for you.

**Comment by naja7host** [comment]
It work now ....

**Comment by BnMcG** [comment]
Good to hear - thanks for raising the incorrect error code with us!
